pull_request_rules:
  - name: Dependabot automatic merge
    conditions:
      - "author=dependabot[bot]"
      - "check-success=ci/semaphoreci/pr: Build Components"
      - "check-success=ci/semaphoreci/pr: Install Dependencies"
      - "check-success=ci/semaphoreci/pr: Run Linting"
      - "#check-success>=4"
      - "#check-failure=0"
    actions:
      merge:
        method: rebase
  - name: Dependabot request reviews
    conditions:
      - "author=dependabot[bot]"
      - "#check-failure>=1"
    actions:
      request_reviews:
        users:
          - RobBrazier